
package com.umbc.aos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoadServiceImplService", targetNamespace = "http://service.aos.umbc.com/", wsdlLocation = "http://192.168.0.7:8080/LoadBalancerService/loadService?wsdl")
public class LoadServiceImplService
    extends Service
{

    private final static URL LOADSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOADSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOADSERVICEIMPLSERVICE_QNAME = new QName("http://service.aos.umbc.com/", "LoadServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.7:8080/LoadBalancerService/loadService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOADSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOADSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LoadServiceImplService() {
        super(__getWsdlLocation(), LOADSERVICEIMPLSERVICE_QNAME);
    }

    public LoadServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOADSERVICEIMPLSERVICE_QNAME, features);
    }

    public LoadServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOADSERVICEIMPLSERVICE_QNAME);
    }

    public LoadServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOADSERVICEIMPLSERVICE_QNAME, features);
    }

    public LoadServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoadServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoadServiceImpl
     */
    @WebEndpoint(name = "LoadServiceImplPort")
    public LoadServiceImpl getLoadServiceImplPort() {
        return super.getPort(new QName("http://service.aos.umbc.com/", "LoadServiceImplPort"), LoadServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoadServiceImpl
     */
    @WebEndpoint(name = "LoadServiceImplPort")
    public LoadServiceImpl getLoadServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.aos.umbc.com/", "LoadServiceImplPort"), LoadServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOADSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOADSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOADSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
