
package com.umbc.aos.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoadServiceImpl", targetNamespace = "http://service.aos.umbc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoadServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FindServer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindServer", targetNamespace = "http://service.aos.umbc.com/", className = "com.umbc.aos.service.FindServer")
    @ResponseWrapper(localName = "FindServerResponse", targetNamespace = "http://service.aos.umbc.com/", className = "com.umbc.aos.service.FindServerResponse")
    @Action(input = "http://service.aos.umbc.com/LoadServiceImpl/FindServerRequest", output = "http://service.aos.umbc.com/LoadServiceImpl/FindServerResponse")
    public String findServer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
