
package com.umbc.aos.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistryService", targetNamespace = "http://ws.aos.umbc.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddService")
    @WebResult(partName = "return")
    @Action(input = "http://ws.aos.umbc.com/RegistryService/AddServiceRequest", output = "http://ws.aos.umbc.com/RegistryService/AddServiceResponse")
    public boolean addService(
        @WebParam(name = "arg0", partName = "arg0")
        WebServiceBean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteService")
    @WebResult(partName = "return")
    @Action(input = "http://ws.aos.umbc.com/RegistryService/DeleteServiceRequest", output = "http://ws.aos.umbc.com/RegistryService/DeleteServiceResponse")
    public boolean deleteService(
        @WebParam(name = "arg0", partName = "arg0")
        WebServiceBean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.umbc.aos.ws.ListofWebserviceBean
     */
    @WebMethod(operationName = "SearchService")
    @WebResult(partName = "return")
    @Action(input = "http://ws.aos.umbc.com/RegistryService/SearchServiceRequest", output = "http://ws.aos.umbc.com/RegistryService/SearchServiceResponse")
    public ListofWebserviceBean searchService(
        @WebParam(name = "arg0", partName = "arg0")
        WebServiceBean arg0);

}
